[build.environment]
NODE_VERSION = "18"

[build]
command = "pnpm build:site"
publish = "packages/site/dist"

[dev]
command = "pnpm dev"
publish = "packages/site/dist"
targetPort = 4321

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[functions]
directory = "packages/functions"
node_bundler = "esbuild"
